version: "3.9"
services:
  frontend:
    build: .
  nginx:
    build: ./nginx
    depends_on:
      - frontend
    restart: always
    ports:
    - "7777:80"
    volumes:
    - "/home/toannv/bss/devops/tictac/public:/var/www/html"